lib/hello_api_web/router.ex
defmodule HelloApiWeb.Router do
  use HelloApiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloApiWeb do
    pipe_through :browser

    resources "/", PageController, only: [:create, :index]

    resources "/users", UserController

    resources "/board", BoardController do
      resources "/reply", ReplyController
    end


  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloApiWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HelloApiWeb.Telemetry
    end
  end
end

lib/hello_api_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace-of-mind from prototype to production</p>
</section>


<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

<section class="row">
  <%= form_for @conn, Routes.page_path(@conn, :create), [as: :user], fn f -> %>
      <div>
        <label for="id">id</label>
        <%= text_input f, :userid, placeholder: "id" %>
        <%= error_tag f, :userid %>
      </div>

      <div>
        <label for="password">Password</label>
        <%= password_input f, :password, placeholder: "Password" %>
        <%= error_tag f, :password %>
      </div>
      
      <%= submit "LOGIN" %>
  <% end %>

  <span><%= link "회원가입", to: Routes.user_path(@conn, :new) %></span>
</section>