lib/hello_api_web/router.ex
defmodule HelloApiWeb.Router do
  use HelloApiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloApiWeb do
    pipe_through :browser

    resources "/", PageController, only: [:create, :index]

    resources "/users", UserController

    resources "/board", BoardController do
      resources "/reply", ReplyController
    end


  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloApiWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HelloApiWeb.Telemetry
    end
  end
end

lib/hello_api/scheme/reply.ex
defmodule HelloApi.Scheme.Reply do
  use Ecto.Schema
  import Ecto.Changeset

  schema "reply" do
    field :comment, :string
    field :board_key, :integer
    field :user_key, :integer

    timestamps()
  end

  @doc false
  def changeset(reply, attrs) do

    IO.puts("Scheme.Reply  changeset")

    reply
    |> cast(attrs, [:comment, :user_key, :board_key])
    |> validate_required([:comment])
  end
end

lib/hello_api_web/controllers/reply_controller.ex
defmodule HelloApiWeb.ReplyController do
  use HelloApiWeb, :controller

  alias HelloApi.Scheme
  alias HelloApi.Scheme.Reply

  def index(conn, _params) do

    IO.puts("ReplyController index === ")
    reply = Scheme.list_reply()
    render(conn, "index.html", reply: reply)
  end

  def new(conn, %{"board_id" => board_key}) do

    changeset = Scheme.change_reply(%Reply{})
    render(conn, "new.html", changeset: changeset, board_key: board_key)

  end

  def create(conn, %{"board_id"=> board_key, "reply" => reply_params}) do

    user_key = get_session(conn, :current_user)

    reply_params = Map.put(reply_params, "board_key", board_key)
    reply_params = Map.put(reply_params, "user_key", user_key)

    case Scheme.create_reply(reply_params) do
      {:ok, reply} ->
        board = Scheme.get_board!(board_key)
        conn
        |> put_flash(:info, "Reply created successfully.")
        |> redirect(to: Routes.board_path(conn, :show, board))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:erroe, "Reply fail.")
    end
  end

  # def show(conn, %{"id" => id}) do
  #   reply = Scheme.get_reply!(id)
  #   render(conn, "show.html", reply: reply)
  # end

  # def edit(conn, %{"id" => id}) do
  #   reply = Scheme.get_reply!(id)
  #   changeset = Scheme.change_reply(reply)
  #   render(conn, "edit.html", reply: reply, changeset: changeset)
  # end

  # def update(conn, %{"id" => id, "reply" => reply_params}) do
  #   reply = Scheme.get_reply!(id)

  #   case Scheme.update_reply(reply, reply_params) do
  #     {:ok, reply} ->
  #       conn
  #       |> put_flash(:info, "Reply updated successfully.")
  #       #|> redirect(to: Routes.reply_path(conn, :show, reply))

  #     {:error, %Ecto.Changeset{} = changeset} ->
  #       render(conn, "edit.html", reply: reply, changeset: changeset)
  #   end
  # end

  # def delete(conn, %{"id" => id}) do
  #   reply = Scheme.get_reply!(id)
  #   {:ok, _reply} = Scheme.delete_reply(reply)

  #   conn
  #   |> put_flash(:info, "Reply deleted successfully.")
  #   #|> redirect(to: Routes.reply_path(conn, :index))
  # end
end

lib/hello_api_web/views/reply_view.ex
defmodule HelloApiWeb.ReplyView do
  use HelloApiWeb, :view
end

lib/hello_api_web/templates/reply/edit.html.eex
<h1>Edit Reply</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.board_reply_path(@conn, :update, @reply)) %>

<%# <span><%= link "Back", to: Routes.board_reply_path(@conn, :index) %></span> %>

lib/hello_api_web/templates/reply/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :comment %>
  <%= text_input f, :comment %>
  <%= error_tag f, :comment %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/hello_api_web/templates/reply/index.html.eex
<h1>Listing Reply</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for reply <- @reply do %>
    <tr>
      <td><%= reply.comment %></td>

      <td>
        <span><%= link "Show", to: Routes.board_reply_path(@conn, :show, reply) %></span>
        <span><%= link "Edit", to: Routes.board_reply_path(@conn, :edit, reply) %></span>
        <span><%= link "Delete", to: Routes.board_reply_path(@conn, :delete, reply), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Reply", to: Routes.board_reply_path(@conn, :new) %></span>

lib/hello_api_web/templates/reply/new.html.eex
<h1>New Reply</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.board_reply_path(@conn, :create, @board_key)) %>

<%# 
<span><%= link "Back", to: Routes.board_reply_path(@conn, :index) %></span> %> %>

lib/hello_api_web/templates/reply/show.html.eex
<h1>Show Reply</h1>

<ul>

  <li>
    <strong>Comment:</strong>
    <%= @reply.comment %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.board_reply_path(@conn, :edit, @reply) %></span>
<span><%= link "Back", to: Routes.board_reply_path(@conn, :index) %></span>